//! Phase 4 M1 wire contract for `mili-viz` (the from-scratch griz
//! replacement). Generated by `build.rs` from the frozen
//! `proto/mili_viz.proto` (consolidated M1 surface — see
//! `planning/mili-viz/phase-4-m1.md` Decision 1, deltas Δ1–Δ9).
//!
//! This crate is types-only: the service trait, the client, and every
//! message. The server lives in `mili-viz-server`; the renderer client
//! is Phase 5. The contract is FROZEN at M1 — `mili-rs` wiring, real
//! geometry, the renderer, and the LLM backend are M2+/M6.

#![allow(clippy::pedantic)]

/// The `mili_viz.v1` package: `MiliViz` service + all M1 messages.
pub mod v1 {
    // Generated code: prost/tonic codegen is not clippy-clean and is
    // not ours to lint (the .proto is the reviewed artifact).
    #![allow(clippy::all, clippy::pedantic, clippy::nursery)]

    tonic::include_proto!("mili_viz.v1");

    /// Semver of the proto contract this build implements. `Hello`
    /// negotiates against the client's `HelloRequest.protocol_version`
    /// (major must match — see `mili-viz-server`).
    pub const PROTOCOL_VERSION: &str = "1.0.0";

    /// Reserved `capabilities` value: present in `HelloReply` iff the
    /// server has an LLM backend configured (phase-4-m1.md Decision 1
    /// Δ9 / Decision 6). The client keys the AI Assistant panel's
    /// existence off it.
    pub const CAP_AGENT: &str = "agent";
}

/// The canonical Apache Arrow `arrow.flight.protocol` package: the
/// standard `FlightService` + its messages, generated from the
/// vendored `proto/Flight.proto` (Apache-2.0). M6's bulk-geometry
/// transport (phase-4-m6.md Decision 26): a separate, wire-standard
/// service co-served next to `MiliViz`. `mili-viz-server` implements
/// only `DoGet` (the frozen `GeometryRef.flight_ticket` → the
/// byte-stable M2/M3 blob); every other Flight RPC is `UNIMPLEMENTED`.
pub mod flight {
    #![allow(clippy::all, clippy::pedantic, clippy::nursery)]

    tonic::include_proto!("arrow.flight.protocol");
}

pub use v1::mili_viz_client;
pub use v1::mili_viz_server;
