#!/usr/bin/env bash
# Regenerate the `griz._proto` gRPC stubs from the ONE canonical proto.
#
# The Python scripting client (Phase 6) MUST consume the exact same
# wire contract as the Rust side — `crates/mili-viz-proto/proto/
# mili_viz.proto` — so the contract cannot drift between clients. This
# is the Python analogue of the Rust `protox` build.rs: the generated
# modules are BUILD OUTPUT — `.gitignore`d, regenerated, never
# hand-edited (planning/mili-viz/phase-6-m1.md Decisions 36 & 53).
#
# Idempotent; safe to re-run. Usage:
#   pip install -e python/pygriz[dev]   # provides grpcio-tools
#   scripts/gen-pygriz-stubs.sh
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

proto_dir="crates/mili-viz-proto/proto"
proto="mili_viz.proto"
out="python/pygriz/src/griz/_proto"
python_bin="${PYTHON:-python3}"

if ! "$python_bin" -c "import grpc_tools" 2>/dev/null; then
  echo "error: grpcio-tools not importable — run 'pip install -e python/pygriz[dev]'" >&2
  exit 1
fi

rm -rf "$out"
mkdir -p "$out"

"$python_bin" -m grpc_tools.protoc \
  -I "$proto_dir" \
  --python_out="$out" \
  --grpc_python_out="$out" \
  --pyi_out="$out" \
  "$proto"

# grpc_tools emits a top-level `import mili_viz_pb2` in the *_grpc
# module; rewrite it to a package-relative import so `griz._proto`
# is self-contained on `sys.path` without leaking a bare top-level
# module name (Decision 53).
grpc_mod="$out/mili_viz_pb2_grpc.py"
"$python_bin" - "$grpc_mod" <<'PY'
import re, sys
p = sys.argv[1]
src = open(p).read()
src = re.sub(r'^import mili_viz_pb2 as',
             'from griz._proto import mili_viz_pb2 as',
             src, flags=re.M)
open(p, "w").write(src)
PY

cat > "$out/__init__.py" <<'PY'
"""Generated gRPC stubs for the frozen mili-viz-proto contract.

BUILD OUTPUT — regenerated by scripts/gen-pygriz-stubs.sh from the one
canonical crates/mili-viz-proto/proto/mili_viz.proto, .gitignore'd,
never hand-edited (planning/mili-viz/phase-6-m1.md Decisions 36 & 53).
"""

from griz._proto import mili_viz_pb2, mili_viz_pb2_grpc

__all__ = ["mili_viz_pb2", "mili_viz_pb2_grpc"]
PY

echo "==> pygriz stubs regenerated into $out from $proto_dir/$proto"
